import type { Metadata } from 'next';
import { TransactionsPageWrapper } from '@/components/wrappers/transactions-page-wrapper';

export const metadata: Metadata = {
  title: 'Transactions | RemitFlow Admin',
  description: 'View and manage all transactions',
};

const mockTransactions = [
  {
    id: 'TXN-001',
    reference: 'REF-001',
    status: 'completed' as const,
    sendAmount: 500,
    sendCurrency: 'GBP',
    receiveAmount: 825000,
    receiveCurrency: 'NGN',
    exchangeRate: 1650,
    fee: 4.99,
    senderId: 'user-001',
    senderName: 'John Smith',
    senderPhone: '+44 7700 900000',
    recipientId: 'rcpt-001',
    recipientName: 'Adebayo Okonkwo',
    recipientBank: 'GTBank',
    recipientAccount: '****5678',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'TXN-002',
    reference: 'REF-002',
    status: 'processing' as const,
    sendAmount: 250,
    sendCurrency: 'GBP',
    receiveAmount: 412500,
    receiveCurrency: 'NGN',
    exchangeRate: 1650,
    fee: 3.99,
    senderId: 'user-002',
    senderName: 'Sarah Johnson',
    senderPhone: '+44 7700 900001',
    recipientId: 'rcpt-002',
    recipientName: 'Chioma Eze',
    recipientBank: 'First Bank',
    recipientAccount: '****1234',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'TXN-003',
    reference: 'REF-003',
    status: 'pending' as const,
    sendAmount: 1000,
    sendCurrency: 'GBP',
    receiveAmount: 1650000,
    receiveCurrency: 'NGN',
    exchangeRate: 1650,
    fee: 7.99,
    senderId: 'user-003',
    senderName: 'Michael Brown',
    senderPhone: '+44 7700 900002',
    recipientId: 'rcpt-003',
    recipientName: 'Emeka Nwosu',
    recipientBank: 'Zenith Bank',
    recipientAccount: '****9012',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'TXN-004',
    reference: 'REF-004',
    status: 'failed' as const,
    sendAmount: 750,
    sendCurrency: 'GBP',
    receiveAmount: 1237500,
    receiveCurrency: 'NGN',
    exchangeRate: 1650,
    fee: 5.99,
    senderId: 'user-004',
    senderName: 'Emma Wilson',
    senderPhone: '+44 7700 900003',
    recipientId: 'rcpt-004',
    recipientName: 'Oluwaseun Adeyemi',
    recipientBank: 'Access Bank',
    recipientAccount: '****3456',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 82800000).toISOString(),
    failureReason: 'Invalid account number',
  },
  {
    id: 'TXN-005',
    reference: 'REF-005',
    status: 'completed' as const,
    sendAmount: 300,
    sendCurrency: 'GBP',
    receiveAmount: 495000,
    receiveCurrency: 'NGN',
    exchangeRate: 1650,
    fee: 3.99,
    senderId: 'user-005',
    senderName: 'David Lee',
    senderPhone: '+44 7700 900004',
    recipientId: 'rcpt-005',
    recipientName: 'Ngozi Okoro',
    recipientBank: 'UBA',
    recipientAccount: '****7890',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 169200000).toISOString(),
    completedAt: new Date(Date.now() - 169200000).toISOString(),
  },
];

export default async function TransactionsPage() {
  return <TransactionsPageWrapper transactions={mockTransactions} />;
}
